Main: obj/Main.o obj/Fabrica.o obj/ControladorUsuario.o obj/ControladorProducto.o obj/ControladorPromocion.o obj/ControladorNotificacion.o obj/ControladorCompra.o obj/DTFecha.o obj/DTDireccion.o obj/DTUsuario.o obj/DTCliente.o obj/DTProducto.o obj/DTVendedor.o obj/DTNotificacion.o obj/DTComentario.o obj/DTRegistroProducto.o obj/DTProductoPromo.o obj/DTCompra.o	obj/DTPromocion.o obj/Producto.o obj/Vendedor.o	obj/Usuario.o	obj/Cliente.o	obj/Compra.o	obj/RegistroProducto.o obj/InfoPromoProducto.o	obj/Promocion.o	obj/Comentario.o		
	g++ obj/Main.o obj/Fabrica.o obj/ControladorUsuario.o obj/ControladorProducto.o obj/ControladorPromocion.o obj/ControladorNotificacion.o obj/ControladorCompra.o obj/DTFecha.o obj/DTDireccion.o obj/DTUsuario.o obj/DTCliente.o obj/DTProducto.o obj/DTVendedor.o obj/DTNotificacion.o obj/DTComentario.o	obj/DTRegistroProducto.o obj/DTProductoPromo.o	obj/DTCompra.o	obj/DTPromocion.o obj/Producto.o obj/Vendedor.o	obj/Usuario.o	obj/Cliente.o obj/Compra.o	obj/RegistroProducto.o obj/InfoPromoProducto.o obj/Promocion.o obj/Comentario.o -o Main

obj/Main.o: Main.cpp
	g++ -c Main.cpp -o obj/Main.o

obj/Fabrica.o: src/fabrica/Fabrica.cpp include/fabrica/Fabrica.hh
	g++ -c src/fabrica/Fabrica.cpp -o obj/Fabrica.o

obj/ControladorUsuario.o: src/controladores/ControladorUsuario.cpp include/controladores/ControladorUsuario.hh
	g++ -c src/controladores/ControladorUsuario.cpp -o obj/ControladorUsuario.o	

obj/ControladorProducto.o: src/controladores/ControladorProducto.cpp include/controladores/ControladorProducto.hh
	g++ -c src/controladores/ControladorProducto.cpp -o obj/ControladorProducto.o	

obj/ControladorPromocion.o: src/controladores/ControladorPromocion.cpp include/controladores/ControladorPromocion.hh
	g++ -c src/controladores/ControladorPromocion.cpp -o obj/ControladorPromocion.o	

obj/ControladorNotificacion.o: src/controladores/ControladorNotificacion.cpp include/controladores/ControladorNotificacion.hh
	g++ -c src/controladores/ControladorNotificacion.cpp -o obj/ControladorNotificacion.o	

obj/ControladorCompra.o: src/controladores/ControladorCompra.cpp include/controladores/ControladorCompra.hh
	g++ -c src/controladores/ControladorCompra.cpp -o obj/ControladorCompra.o	

obj/DTFecha.o: src/datatypes/DTFecha.cpp include/datatypes/DTFecha.hh
	g++ -c src/datatypes/DTFecha.cpp -o obj/DTFecha.o

obj/DTDireccion.o: src/datatypes/DTDireccion.cpp include/datatypes/DTDireccion.hh
	g++ -c src/datatypes/DTDireccion.cpp -o obj/DTDireccion.o	

obj/DTUsuario.o: src/datatypes/DTUsuario.cpp include/datatypes/DTUsuario.hh
	g++ -c src/datatypes/DTUsuario.cpp -o obj/DTUsuario.o	

obj/DTCliente.o: src/datatypes/DTCliente.cpp include/datatypes/DTCliente.hh
	g++ -c src/datatypes/DTCliente.cpp -o obj/DTCliente.o

obj/DTProducto.o: src/datatypes/DTProducto.cpp include/datatypes/DTProducto.hh
	g++ -c src/datatypes/DTProducto.cpp -o obj/DTProducto.o	

obj/DTVendedor.o: src/datatypes/DTVendedor.cpp include/datatypes/DTVendedor.hh
	g++ -c src/datatypes/DTVendedor.cpp -o obj/DTVendedor.o	

obj/DTNotificacion.o: src/datatypes/DTNotificacion.cpp include/datatypes/DTNotificacion.hh
	g++ -c src/datatypes/DTNotificacion.cpp -o obj/DTNotificacion.o	

obj/DTComentario.o: src/datatypes/DTComentario.cpp include/datatypes/DTComentario.hh
	g++ -c src/datatypes/DTComentario.cpp -o obj/DTComentario.o	

obj/DTRegistroProducto.o: src/datatypes/DTRegistroProducto.cpp include/datatypes/DTRegistroProducto.hh
	g++ -c src/datatypes/DTRegistroProducto.cpp -o obj/DTRegistroProducto.o	

obj/DTProductoPromo.o: src/datatypes/DTProductoPromo.cpp include/datatypes/DTProductoPromo.hh
	g++ -c src/datatypes/DTProductoPromo.cpp -o obj/DTProductoPromo.o

obj/DTCompra.o: src/datatypes/DTCompra.cpp include/datatypes/DTCompra.hh
	g++ -c src/datatypes/DTCompra.cpp -o obj/DTCompra.o

obj/DTPromocion.o: src/datatypes/DTPromocion.cpp include/datatypes/DTPromocion.hh
	g++ -c src/datatypes/DTPromocion.cpp -o obj/DTPromocion.o

obj/Producto.o: src/Producto.cpp include/Producto.hh
	g++ -c src/Producto.cpp -o obj/Producto.o

obj/Vendedor.o: src/Vendedor.cpp include/Vendedor.hh
	g++ -c src/Vendedor.cpp -o obj/Vendedor.o	

obj/Usuario.o: src/Usuario.cpp include/Usuario.hh
	g++ -c src/Usuario.cpp -o obj/Usuario.o	

obj/Cliente.o: src/Cliente.cpp include/Cliente.hh
	g++ -c src/Cliente.cpp -o obj/Cliente.o	

obj/Compra.o: src/Compra.cpp include/Compra.hh
	g++ -c src/Compra.cpp -o obj/Compra.o	

obj/RegistroProducto.o: src/RegistroProducto.cpp include/RegistroProducto.hh
	g++ -c src/RegistroProducto.cpp -o obj/RegistroProducto.o

obj/InfoPromoProducto.o: src/InfoPromoProducto.cpp include/InfoPromoProducto.hh
	g++ -c src/InfoPromoProducto.cpp -o obj/InfoPromoProducto.o

obj/Promocion.o: src/Promocion.cpp include/Promocion.hh
	g++ -c src/Promocion.cpp -o obj/Promocion.o

obj/Comentario.o: src/Comentario.cpp include/Comentario.hh
	g++ -c src/Comentario.cpp -o obj/Comentario.o

clean:
	@rm -f obj/*.o Main

